"""
GENERATED by python/tools/gen_telemetry_schema.py from telemetry_schema.json -- DO NOT EDIT BY HAND.

Constants + id<->name maps for the generic sensor telemetry frame
(docs/SENSOR_TELEMETRY_FRAME_PLAN.md S2). Consumed by the section-list
decoder (common/telemetry_frame.py). CHANNEL_NAME_BY_ID maps an opaque
wire channel_id to the SensorChannel value string downstream code
(features.py / registry) keys SensorFrame.bins by.
"""

SOURCE_ID = {
    "base_station": 0,
    "satellite": 1
}

DATA_KIND = {
    "SPECTRUM": 1,
    "TIME_SERIES": 2,
    "SCALAR_SET": 3
}

CHANNEL_ID_BY_NAME = {
    "mic": 0,
    "accel": 1,
    "accel_x_raw": 2,
    "accel_y_raw": 3,
    "accel_z_raw": 4,
    "mic_raw": 5,
    "accel_x": 6,
    "accel_y": 7,
    "accel_z": 8
}

CHANNEL_NAME_BY_ID = {
    "0": "mic",
    "1": "accel",
    "2": "accel_x_raw",
    "3": "accel_y_raw",
    "4": "accel_z_raw",
    "5": "mic_raw",
    "6": "accel_x",
    "7": "accel_y",
    "8": "accel_z"
}
# JSON object keys are strings; re-key to int for wire (u8) lookups.
CHANNEL_NAME_BY_ID = {int(k): v for k, v in CHANNEL_NAME_BY_ID.items()}

CHANNEL_KIND_BY_ID = {
    "0": "SPECTRUM",
    "1": "SPECTRUM",
    "2": "TIME_SERIES",
    "3": "TIME_SERIES",
    "4": "TIME_SERIES",
    "5": "TIME_SERIES",
    "6": "SPECTRUM",
    "7": "SPECTRUM",
    "8": "SPECTRUM"
}
CHANNEL_KIND_BY_ID = {int(k): v for k, v in CHANNEL_KIND_BY_ID.items()}

PERF_CHANNEL_ID = 255

SCALAR_ID_BY_NAME = {
    "rms": 1,
    "kurtosis": 2,
    "crest_factor": 3,
    "peak": 4,
    "std": 5,
    "skewness": 6,
    "rms_x": 7,
    "kurtosis_x": 8,
    "std_x": 9,
    "peak_x": 10,
    "crest_factor_x": 11,
    "skewness_x": 12,
    "rms_y": 13,
    "kurtosis_y": 14,
    "std_y": 15,
    "peak_y": 16,
    "crest_factor_y": 17,
    "skewness_y": 18,
    "rms_z": 19,
    "kurtosis_z": 20,
    "std_z": 21,
    "peak_z": 22,
    "crest_factor_z": 23,
    "skewness_z": 24,
    "rms_mic": 25,
    "kurtosis_mic": 26,
    "std_mic": 27,
    "peak_mic": 28,
    "crest_factor_mic": 29,
    "skewness_mic": 30
}
SCALAR_NAME_BY_ID = {v: k for k, v in SCALAR_ID_BY_NAME.items()}
