#!/usr/bin/env python3
"""
Code generator for the generic sensor telemetry frame schema
(docs/SENSOR_TELEMETRY_FRAME_PLAN.md S2, T1 in the reference repo).

Reads the single source of truth (schema/telemetry_schema.json) and emits
every side so they cannot drift:

  - components/epm_codec/include/frame_codec/telemetry_schema.h -- #defines
                                        for the satellite firmware's section
                                        writer (frame_codec/spectrum_codec.c)
  - gateway/common/telemetry_schema.py -- constants + id<->name maps for the
                                        gateway-side frame decoder

Run after editing the JSON:

    python schema/gen_schema.py

Both generated files are checked in (so a fresh clone / firmware build works
without running this first); running it is only needed after a schema edit.
The generator refuses to emit anything if the JSON is internally inconsistent
(duplicate ids, a channel `kind` not in `data_kinds`, ...), so a bad edit
fails loudly here rather than silently mis-generating one side.

Ported from the reference repo's base-station/python/tools/gen_telemetry_schema.py
(same validation + rendering logic); paths adjusted for this repo's layout,
which has no base-station-sketch equivalent and a mic_tools/ gateway (not yet
gateway/ -- that split happens in Phase 8).

No third-party deps (stdlib json only).
"""
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.normpath(os.path.join(_HERE, ".."))
SCHEMA_PATH = os.path.join(_HERE, "telemetry_schema.json")
FIRMWARE_HEADER_PATH = os.path.join(_REPO_ROOT, "components", "epm_codec", "include",
                                     "frame_codec", "telemetry_schema.h")
PYMOD_PATH = os.path.join(_REPO_ROOT, "gateway", "common", "telemetry_schema.py")

_GEN_BANNER = "GENERATED by schema/gen_schema.py from telemetry_schema.json -- DO NOT EDIT BY HAND."


def _c_ident(name: str) -> str:
    """A channel/source/scalar name -> UPPER_SNAKE C identifier fragment."""
    return name.strip().upper().replace("-", "_").replace(" ", "_")


def load_schema(path: str = SCHEMA_PATH) -> dict:
    with open(path) as f:
        schema = json.load(f)
    _validate(schema)
    return schema


def _validate(schema: dict) -> None:
    """Fail loudly on the mistakes a hand-edit is most likely to introduce,
    so one side can't be generated from an inconsistent schema."""
    kinds = schema["data_kinds"]
    for kind_name, kind_val in kinds.items():
        if not (0 <= kind_val <= 255):
            raise ValueError(f"data_kind {kind_name}={kind_val} out of u8 range")

    seen_ch_ids = {}
    seen_ch_names = {}
    for ch in schema["channels"]:
        cid, name, kind = ch["id"], ch["name"], ch["kind"]
        if not (0 <= cid <= 255):
            raise ValueError(f"channel {name!r} id={cid} out of u8 range")
        if kind not in kinds:
            raise ValueError(f"channel {name!r} kind={kind!r} not in data_kinds {sorted(kinds)}")
        if cid in seen_ch_ids:
            raise ValueError(f"duplicate channel id {cid}: {seen_ch_ids[cid]!r} and {name!r}")
        if name in seen_ch_names:
            raise ValueError(f"duplicate channel name {name!r}")
        seen_ch_ids[cid] = name
        seen_ch_names[name] = cid

    perf_id = schema["perf_channel_id"]
    if perf_id in seen_ch_ids:
        raise ValueError(f"perf_channel_id {perf_id} collides with channel {seen_ch_ids[perf_id]!r}")

    seen_scalar_ids = {}
    for sname, sid in schema["scalars"].items():
        if not (0 <= sid <= 65535):
            raise ValueError(f"scalar {sname!r} id={sid} out of u16 range")
        if sid in seen_scalar_ids:
            raise ValueError(f"duplicate scalar id {sid}: {seen_scalar_ids[sid]!r} and {sname!r}")
        seen_scalar_ids[sid] = sname


def render_header(schema: dict) -> str:
    lines = [
        "/*",
        f" * {_GEN_BANNER}",
        " *",
        " * Wire constants for the generic sensor telemetry frame",
        " * (docs/SENSOR_TELEMETRY_FRAME_PLAN.md S3, Phase A). Included by every",
        " * section-list writer (base-station sketch/fuser.cpp, satellite",
        " * frame_codec/spectrum_codec.cpp). All frame integers are little-endian.",
        " */",
        "#ifndef TELEMETRY_SCHEMA_H",
        "#define TELEMETRY_SCHEMA_H",
        "",
        "/* source_id: which node produced the frame (opaque numeric identity). */",
    ]
    for name, val in schema["sources"].items():
        lines.append(f"#define TELEM_SOURCE_{_c_ident(name)} {val}")
    lines += [
        "",
        "/* data_kind: how to decode a section's body. */",
    ]
    for name, val in schema["data_kinds"].items():
        lines.append(f"#define TELEM_KIND_{_c_ident(name)} {val}")
    lines += [
        "",
        "/* channel_id: opaque per-channel identity (meaning lives in the schema, not here). */",
    ]
    for ch in schema["channels"]:
        lines.append(f"#define TELEM_CHANNEL_{_c_ident(ch['name'])} {ch['id']}")
    lines.append(f"#define TELEM_CHANNEL_PERF {schema['perf_channel_id']}")
    lines += [
        "",
        "/* scalar ids for SCALAR_SET bodies (u16 keys against the schema). */",
    ]
    for name, val in schema["scalars"].items():
        lines.append(f"#define TELEM_SCALAR_{_c_ident(name)} {val}")
    lines += ["", "#endif  /* TELEMETRY_SCHEMA_H */", ""]
    return "\n".join(lines)


def render_pymodule(schema: dict) -> str:
    channels_by_id = {ch["id"]: ch["name"] for ch in schema["channels"]}
    channel_kind_by_id = {ch["id"]: ch["kind"] for ch in schema["channels"]}
    lines = [
        '"""',
        _GEN_BANNER,
        "",
        "Constants + id<->name maps for the generic sensor telemetry frame",
        "(docs/SENSOR_TELEMETRY_FRAME_PLAN.md S2). Consumed by the section-list",
        "frame decoder. CHANNEL_NAME_BY_ID maps an opaque wire channel_id to the",
        "channel name downstream code keys decoded sections by.",
        '"""',
        "",
        f"SOURCE_ID = {json.dumps(schema['sources'], indent=4)}",
        "",
        f"DATA_KIND = {json.dumps(schema['data_kinds'], indent=4)}",
        "",
        f"CHANNEL_ID_BY_NAME = {json.dumps({ch['name']: ch['id'] for ch in schema['channels']}, indent=4)}",
        "",
        f"CHANNEL_NAME_BY_ID = {json.dumps({str(k): v for k, v in channels_by_id.items()}, indent=4)}",
        "# JSON object keys are strings; re-key to int for wire (u8) lookups.",
        "CHANNEL_NAME_BY_ID = {int(k): v for k, v in CHANNEL_NAME_BY_ID.items()}",
        "",
        f"CHANNEL_KIND_BY_ID = {json.dumps({str(k): v for k, v in channel_kind_by_id.items()}, indent=4)}",
        "CHANNEL_KIND_BY_ID = {int(k): v for k, v in CHANNEL_KIND_BY_ID.items()}",
        "",
        f"PERF_CHANNEL_ID = {schema['perf_channel_id']}",
        "",
        f"SCALAR_ID_BY_NAME = {json.dumps(schema['scalars'], indent=4)}",
        "SCALAR_NAME_BY_ID = {v: k for k, v in SCALAR_ID_BY_NAME.items()}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    schema = load_schema()

    header = render_header(schema)
    pymod = render_pymodule(schema)

    with open(FIRMWARE_HEADER_PATH, "w") as f:
        f.write(header)
    with open(PYMOD_PATH, "w") as f:
        f.write(pymod)

    print(f"wrote {os.path.relpath(FIRMWARE_HEADER_PATH, _REPO_ROOT)}")
    print(f"wrote {os.path.relpath(PYMOD_PATH, _REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
