/*
 * GENERATED by python/tools/gen_telemetry_schema.py from telemetry_schema.json -- DO NOT EDIT BY HAND.
 *
 * Wire constants for the generic sensor telemetry frame
 * (docs/SENSOR_TELEMETRY_FRAME_PLAN.md S3, Phase A). Included by
 * fuser.cpp's section-list writer. All frame integers are little-endian.
 */
#ifndef TELEMETRY_SCHEMA_H
#define TELEMETRY_SCHEMA_H

/* source_id: which node produced the frame (opaque numeric identity). */
#define TELEM_SOURCE_BASE_STATION 0
#define TELEM_SOURCE_SATELLITE 1

/* data_kind: how to decode a section's body. */
#define TELEM_KIND_SPECTRUM 1
#define TELEM_KIND_TIME_SERIES 2
#define TELEM_KIND_SCALAR_SET 3

/* channel_id: opaque per-channel identity (meaning lives in the schema, not here). */
#define TELEM_CHANNEL_MIC 0
#define TELEM_CHANNEL_ACCEL 1
#define TELEM_CHANNEL_ACCEL_X_RAW 2
#define TELEM_CHANNEL_ACCEL_Y_RAW 3
#define TELEM_CHANNEL_ACCEL_Z_RAW 4
#define TELEM_CHANNEL_MIC_RAW 5
#define TELEM_CHANNEL_PERF 255

/* scalar ids for SCALAR_SET bodies (u16 keys against the schema). */
#define TELEM_SCALAR_RMS 1
#define TELEM_SCALAR_KURTOSIS 2

#endif  /* TELEMETRY_SCHEMA_H */
