/*
 * GENERATED by schema/gen_schema.py from telemetry_schema.json -- DO NOT EDIT BY HAND.
 *
 * Wire constants for the generic sensor telemetry frame
 * (docs/SENSOR_TELEMETRY_FRAME_PLAN.md S3, Phase A). Included by every
 * section-list writer (base-station sketch/fuser.cpp, satellite
 * frame_codec/spectrum_codec.cpp). All frame integers are little-endian.
 */
#ifndef TELEMETRY_SCHEMA_H
#define TELEMETRY_SCHEMA_H

/* source_id: which node produced the frame (opaque numeric identity). */
#define TELEM_SOURCE_BASE_STATION 0
#define TELEM_SOURCE_SATELLITE 1

/* data_kind: how to decode a section's body. */
#define TELEM_KIND_SPECTRUM 1
#define TELEM_KIND_TIME_SERIES 2
#define TELEM_KIND_SCALAR_SET 3

/* channel_id: opaque per-channel identity (meaning lives in the schema, not here). */
#define TELEM_CHANNEL_MIC 0
#define TELEM_CHANNEL_ACCEL 1
#define TELEM_CHANNEL_ACCEL_X_RAW 2
#define TELEM_CHANNEL_ACCEL_Y_RAW 3
#define TELEM_CHANNEL_ACCEL_Z_RAW 4
#define TELEM_CHANNEL_MIC_RAW 5
#define TELEM_CHANNEL_ACCEL_X 6
#define TELEM_CHANNEL_ACCEL_Y 7
#define TELEM_CHANNEL_ACCEL_Z 8
#define TELEM_CHANNEL_ACCEL_X_ENVELOPE 9
#define TELEM_CHANNEL_ACCEL_Y_ENVELOPE 10
#define TELEM_CHANNEL_ACCEL_Z_ENVELOPE 11
#define TELEM_CHANNEL_PERF 255

/* scalar ids for SCALAR_SET bodies (u16 keys against the schema). */
#define TELEM_SCALAR_RMS 1
#define TELEM_SCALAR_KURTOSIS 2
#define TELEM_SCALAR_CREST_FACTOR 3
#define TELEM_SCALAR_PEAK 4
#define TELEM_SCALAR_STD 5
#define TELEM_SCALAR_SKEWNESS 6
#define TELEM_SCALAR_RMS_X 7
#define TELEM_SCALAR_KURTOSIS_X 8
#define TELEM_SCALAR_STD_X 9
#define TELEM_SCALAR_PEAK_X 10
#define TELEM_SCALAR_CREST_FACTOR_X 11
#define TELEM_SCALAR_SKEWNESS_X 12
#define TELEM_SCALAR_RMS_Y 13
#define TELEM_SCALAR_KURTOSIS_Y 14
#define TELEM_SCALAR_STD_Y 15
#define TELEM_SCALAR_PEAK_Y 16
#define TELEM_SCALAR_CREST_FACTOR_Y 17
#define TELEM_SCALAR_SKEWNESS_Y 18
#define TELEM_SCALAR_RMS_Z 19
#define TELEM_SCALAR_KURTOSIS_Z 20
#define TELEM_SCALAR_STD_Z 21
#define TELEM_SCALAR_PEAK_Z 22
#define TELEM_SCALAR_CREST_FACTOR_Z 23
#define TELEM_SCALAR_SKEWNESS_Z 24
#define TELEM_SCALAR_RMS_MIC 25
#define TELEM_SCALAR_KURTOSIS_MIC 26
#define TELEM_SCALAR_STD_MIC 27
#define TELEM_SCALAR_PEAK_MIC 28
#define TELEM_SCALAR_CREST_FACTOR_MIC 29
#define TELEM_SCALAR_SKEWNESS_MIC 30

#endif  /* TELEMETRY_SCHEMA_H */
