#!/usr/bin/env bash
#
# provision-spi.sh
#
# Gives the app's Python code (running inside the arduino-app-cli-managed
# Docker container) access to the dedicated MCU<->MPU SPI link's master-side
# device node, /dev/spidev0.0.
#
# A plain udev group fix is NOT enough here: /dev is bind-mounted wholesale
# into the app container, but the container isn't privileged and its
# device-cgroup allowlist - regenerated by arduino-app-cli on every
# `app start` from compiled-in logic, with no app.yaml/CLI knob to extend it -
# doesn't include spidev's major number (153, confirmed via
# `ls -la /dev/spidev0.0`). So spidev.open() from inside the container gets
# EPERM at the cgroup layer no matter what file permissions the device node
# has.
#
# The fix: a small root-owned systemd service (host/spi_bridge.py +
# host/spi-bridge.service) that owns the spidev0.0 fd from outside the
# container - where the cgroup restriction doesn't apply - and re-exposes it
# over a Unix domain socket at /dev/spi-link.sock. That path is under /dev,
# which IS already bind-mounted into the container, so the socket needs no
# new compose/bind-mount plumbing and survives every app redeploy untouched.
# App-side Python code (see tests/spi_link_test.py) talks to that socket, not
# to spidev0.0 directly.
#
# This is a SYSTEM-LEVEL, ONE-TIME board provisioning step, OUTSIDE the App
# Lab app: it is NOT applied by deploy.sh and is wiped by an OS reflash -
# re-run it after any base-OS reflash. It installs a root-owned systemd unit
# and an apt package, so it needs the board's sudo password (prompted once
# on-device via sudo -S).
#
# Usage:
#   ./provision-spi.sh
#
# You will be prompted for the board's sudo password.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAEMON_SRC="${SCRIPT_DIR}/host/spi_bridge.py"
UNIT_SRC="${SCRIPT_DIR}/host/spi-bridge.service"
DAEMON_DST="/usr/local/sbin/spi_bridge.py"
UNIT_DST="/etc/systemd/system/spi-bridge.service"

step() { echo; echo "==> $1"; }

ADB_STATE="$(adb get-state 2>/dev/null || true)"
if [ "${ADB_STATE}" != "device" ]; then
    echo "Board not visible to adb (state: '${ADB_STATE:-none}'). Run 'adb devices'." >&2
    exit 1
fi

read -r -s -p "Board sudo password: " SUDO_PW
echo

step "Installing python3-spidev (apt)"
adb shell "echo '${SUDO_PW}' | sudo -S -p '' apt-get install -y python3-spidev"

step "Raising spidev bufsiz (needed for the ~4.1KB fuser frame)"
# spidev's default bufsiz is 4096 - one byte under our 4124-byte SPI frame, so
# an unraised bufsiz rejects a full-frame SPI_IOC_MESSAGE with -EMSGSIZE (and
# py-spidev's xfer2() has its own hardcoded 4096 cap besides - which is why the
# daemon does the transfer via a raw single-message ioctl, see host/spi_bridge.py).
# spidev is a loadable module here, so set the param via modprobe.d + reload.
adb shell "echo '${SUDO_PW}' | sudo -S -p '' bash -c '
  echo \"options spidev bufsiz=65536\" > /etc/modprobe.d/spidev.conf &&
  (rmmod spidev 2>/dev/null || true) && modprobe spidev
'"
adb shell "cat /sys/module/spidev/parameters/bufsiz"

step "Pushing ${DAEMON_DST} and ${UNIT_DST}"
adb push "${DAEMON_SRC}" /tmp/spi_bridge.py >/dev/null
adb push "${UNIT_SRC}" /tmp/spi-bridge.service >/dev/null
adb shell "echo '${SUDO_PW}' | sudo -S -p '' sh -c '
  cp /tmp/spi_bridge.py ${DAEMON_DST} && chmod 755 ${DAEMON_DST} &&
  cp /tmp/spi-bridge.service ${UNIT_DST} &&
  rm -f /tmp/spi_bridge.py /tmp/spi-bridge.service
'"

step "Enabling + (re)starting spi-bridge.service"
adb shell "echo '${SUDO_PW}' | sudo -S -p '' systemctl daemon-reload"
adb shell "echo '${SUDO_PW}' | sudo -S -p '' systemctl enable --now spi-bridge.service"
adb shell "echo '${SUDO_PW}' | sudo -S -p '' systemctl restart spi-bridge.service"

step "Verifying"
adb shell "echo '${SUDO_PW}' | sudo -S -p '' systemctl is-active spi-bridge.service"
adb shell "ls -la /dev/spi-link.sock"
echo
echo "spi-bridge.service is up, exposing /dev/spidev0.0 at /dev/spi-link.sock."
echo "App-side Python connects to that socket (see tests/spi_link_test.py)."
